### ISSUE TITLE
Unc0ver users : App signed with permasign will crash if it contains Frameworks folder

### ISSUE THREAD

**Issue by heinekenpsx** [powenn/permasigneriOS#12]
Executables in Frameworks will not be signed with the Elucubratus's ldid, it only works with the Procursus's ldid

**Comment by powenn** [comment]
I think this already got fixed, which version you using and what app you signed

**Comment by heinekenpsx** [comment]
@powenn i'm using iphone X ios 14.3
All apps that contain frameworks will crash, they are created by your tools or Nebula's tools

**Comment by powenn** [comment]
> @powenn i'm using iphone X ios 14.3
> All apps that contain frameworks will crash, they are created by your tools or Nebula's tools

send me your screenshot , /var/mobile/Documents/permasigneriOS/tmp

**Comment by heinekenpsx** [comment]
@powenn I created an issue response in the Nebula repository
https://github.com/itsnebulalol/permasigner/issues/31

**Comment by heinekenpsx** [comment]
@powenn ahh, permasignios v0.1.7

**Comment by heinekenpsx** [comment]
@powenn https://ibb.co/C9r89nW

**Comment by powenn** [comment]
Did you tried others app ?

**Comment by heinekenpsx** [comment]
@powenn yes, i have tried with many apps

**Comment by powenn** [comment]
That wasn't caused by frameworks 
, I found the problems

**Comment by powenn** [comment]
https://www.icloud.com/iclouddrive/0a7lFxALim4Zk57lmHzZRpc2w#com.powen.permasignerios.0.1

**Comment by baimour** [comment]
我用这个版本试试

**Comment by baimour** [comment]
YouTube+uYou签名成功 但是没有进度条。能在未越狱使用，重启设备和进入越狱，需要的时间比较长，是我装的应用太多了？

**Comment by powenn** [comment]
進度條還有些小問題，所以還沒發佈這版本，簽名過程翻轉裝置才能讓進度條更新

**Comment by baimour** [comment]
OK，进入越狱状态和重启设备黑屏的时间更长了。为什么？

**Comment by powenn** [comment]
?? 你都裝了什麼 ， 這個我真不清楚什麼原因，沒感覺到時間變長

**Comment by baimour** [comment]
好吧，我想是安装了太多不掉签应用

**Comment by powenn** [comment]
裝了多少個呢？

**Comment by baimour** [comment]
> 裝了多少個呢？

才4个

**Comment by heinekenpsx** [comment]
Still not working, app still crashing, the change I see now is the tmp folder has been cleaned up

**Comment by superrnovae** [comment]
> @powenn Still not working, app still crashing, the change I see now is the tmp folder has been cleaned up

it obviously will not work as nothing is being signed. You're only choice is to run the script on macos or linux.   
ldid from procursus can theoretically be installed on any jailbreak, all it needs is to be repackaged with openssl1.1.1 dependency and rpath pointing to local libiosexec.
