### ISSUE TITLE
After installing the plug-in, CLICK Permanent Sign. Why will sign failed appear？

### ISSUE THREAD

**Issue by longxuli** [powenn/permasigneriOS#13]
My system is iOS14.1, 12PRO MAX. After installing the plug-in, CLICK Permanent Sign. Why will sign failed appear？

**Comment by longxuli** [comment]
I think the permanent application is: unc0ver

**Comment by longxuli** [comment]
I also tried YouTube, where SIGN Falied also appeared

**Comment by powenn** [comment]
https://www.icloud.com/iclouddrive/0a7lFxALim4Zk57lmHzZRpc2w#com.powen.permasignerios.0.1

**Comment by longxuli** [comment]
![微信图片_20220712145319](https://user-images.githubusercontent.com/109132126/178427367-e897f033-6230-4b26-9ba6-deca10c097f1.jpg)
I tried 0.1.8 and still had this problem

**Comment by baimour** [comment]
> I also tried YouTube, where SIGN Falied also appeared

Change the app name to 123

**Comment by h0ip** [comment]
Some apps I expected and some fail when I drop them with the tool

**Comment by baimour** [comment]
> Some apps I expected and some fail when I drop them with the tool

After deletion, the data of the application will remain, so

**Comment by h0ip** [comment]
This tool works on all applications or not

**Comment by longxuli** [comment]
I tried to rename the IPA file to 123，The problem continued after a crash

**Comment by powenn** [comment]
Send me the file

**Comment by baimour** [comment]
![927F10DF-B365-42FC-85D9-2FA2E367CD02](https://user-images.githubusercontent.com/85350961/178431319-813ce857-0ccc-40a9-ba07-d8d6d0130294.png)
![BB02A304-A563-4B88-9555-2BD19CDDABF5](https://user-images.githubusercontent.com/85350961/178431551-86126727-670f-4192-ae82-d7b9b32830ff.png)
I have no crash issues

**Comment by longxuli** [comment]
I used the same file on X phone of system 14.3 and everything was normal without this problem, but this problem appeared on 12Promax of system 14.1

**Comment by powenn** [comment]
Received 
First thing, it's not recommend sign unc0ver 8.0.2

But if you want 
Check this 
https://twitter.com/wkartspro/status/1546613764086169600?s=21&t=2HwPQot6vQMD9rnN7mj-aw

The mentioned modifications 

https://twitter.com/powen00hsiao/status/1546011189540700161?s=21&t=2HwPQot6vQMD9rnN7mj-aw

**Comment by powenn** [comment]
Also try clearing folder manually 
Just delete /var/mobile/Documents/permasigneriOS 
And reopen it

**Comment by longxuli** [comment]
I have exported 8.0.2 unc0ver file deb with IPHONE X, installed it in 12Promax, and made it appear on the desktop by some means. Is it permanent signature software now? How do I verify that I have succeeded

**Comment by powenn** [comment]
To check permanent only, reboot device 
If can launch into app, you succeeded 

To check jailbreak working with it , follow the instruction above, you will need AltStore

**Comment by longxuli** [comment]
According to my method, the application is still available after restarting the device. It can be opened, but the jailbreak cannot be completed normally. May I ask what version of UN do you recommend that can be permanently signed by the application on the 14.1 A14 device?

**Comment by powenn** [comment]
try 0.8.1

**Comment by powenn** [comment]
https://twitter.com/powen00hsiao/status/1545698222026665985?s=21&t=2HwPQot6vQMD9rnN7mj-aw

**Comment by longxuli** [comment]
I think I see the difference between the two systems, one of me is missing a folder, but PermasigneriOS can open it
![1657616890575](https://user-images.githubusercontent.com/109132126/178454516-172a22de-4a68-47dc-9008-461674231cbf.jpg)
![20220712170615](https://user-images.githubusercontent.com/109132126/178454559-69c9209e-2388-4d48-8885-55894d80bfac.png)

**Comment by longxuli** [comment]
After I installed PermasigneriOS, there was no PermasigneriOS folder in the Filza folder

**Comment by powenn** [comment]
Yeah you didn't create the path , seems you don't have permission to do that

**Comment by powenn** [comment]
![image](https://user-images.githubusercontent.com/72635554/178456443-4d86edd5-d6cc-4247-a7fd-67cef55d4170.jpeg)


Modify to it as the tweet said

**Comment by longxuli** [comment]
![a8e088609dfe14221c467eec5b4e9aa](https://user-images.githubusercontent.com/109132126/178462870-eaf84e19-3d84-4589-922a-bf9e9b5ea541.jpg)

**Comment by baimour** [comment]
簽名后，只能在越獄狀態打開，重啟后閃退

**Comment by h0ip** [comment]
![image](https://user-images.githubusercontent.com/63618976/179158033-53e58458-6b19-4f8e-92d4-46986bc991c1.png)

**Comment by h0ip** [comment]
This is last update from the tool in iPhone X iOS 14.3 jailbreak Taurine

**Comment by powenn** [comment]
Check did /var/mobile/Documents/permasigneriOS exist 
And /var/mobile/Documents permission

**Comment by h0ip** [comment]
![image](https://user-images.githubusercontent.com/63618976/179177410-2bca3598-1fc5-404a-a17b-e624124aa865.png)

**Comment by h0ip** [comment]
Same problem with signature

**Comment by powenn** [comment]
https://twitter.com/ichitaso/status/1552689879578218496?s=21&t=jk6aejISi2LgmFwFJml_KA

Try 
Uninstall signer
Delete /var/mobile/Documents/permasigneriOS
Run "chown mobile:mobile /var/mobile/Documents" in terminal 
Reinstall signer 
If still not work 
Run "chown -R mobile:mobile /var/mobile/Documents"

**Comment by Saeed11015** [comment]
ت
