### ISSUE TITLE
0.1.8 has no progress bar

### ISSUE THREAD

**Issue by baimour** [powenn/permasigneriOS#16]
點擊簽名後沒有顯示進度，與之前一樣

**Comment by powenn** [comment]
我也沒有
似乎某些裝置異常
6s works fine but 11pro not

**Comment by Lewrin1** [comment]
I don't see the progress bar on my 6s plus

**Comment by Lewrin1** [comment]
> 我也吴有
> ¿A?
> 6s funciona bien, pero 11pro no

I don't see the progress bar on my 6s plus

**Comment by Merculous** [comment]
Not sure I'm really missing it too, however I don't see an actual progress bar with 0.1.8.

**Comment by powenn** [comment]
try 0.1.9
