### ISSUE TITLE
0.1.8 fails to start signing process with v8.0.2 unc0ver

### ISSUE THREAD

**Issue by Merculous** [powenn/permasigneriOS#17]
I had updated to 0.1.8 and I managed to sign another ipa, however now if I try to sign again using the latest release, the button does get clicked but nothing happens. If you spam the button, it says it failed to sign anyway.

My device:  iPhone11,6 14.3, Fugu14 + v8.0.2 unc0ver

**Comment by powenn** [comment]
Actually it happened, try rotate devices , I will try to solve progress bar issues

**Comment by powenn** [comment]
0.1.9 fix sign button
