### ISSUE TITLE
some apps crashes 

### ISSUE THREAD

**Issue by bolognayballs** [powenn/permasigneriOS#18]
Apps crashing after signing with permsigner in non jail broken state iOS 14.4.2 and iPhone XR uncover

**Comment by h0ip** [comment]
The tool is not ready to work, I think that

**Comment by powenn** [comment]
Signer version?
Did every app crashed?

**Comment by baimour** [comment]
我在0.1.10版本，有时候会在越狱状态打开闪退 原因是注入了libsubstrate.dylib，但是如果没有它，在非越狱状态会闪退。在越狱状态，需要修改libsubstrate.dylib名称，越狱状态才能打开

**Comment by powenn** [comment]
能把檔案發給我測試一下嗎

**Comment by powenn** [comment]
> 我在0.1.10版本，有时候会在越狱状态打开闪退 原因是注入了libsubstrate.dylib，但是如果没有它，在非越狱状态会闪退。在越狱状态，需要修改libsubstrate.dylib名称，才能打开

可以的話，幫我把問題也弄個英文版本，因為有些人可能也有一樣的問題，但他們不會中文，這可能造成同樣的問題反覆提問

**Comment by baimour** [comment]
好的，稍等

**Comment by baimour** [comment]
has been sent to your email

**Comment by powenn** [comment]
I received it, But it requires specific app to download, I am not using it, could use share it with others way like iCloud file sharing or google drive etc

**Comment by baimour** [comment]
> 

Hold on

**Comment by powenn** [comment]
I remember that someone sent me tiktok ipa too, it crashes after launch and works for only few seconds in both environments

**Comment by baimour** [comment]
> I remember that someone sent me tiktok ipa too, it crashes after launch and works for only few seconds in both environments

I have never encountered this problem

**Comment by powenn** [comment]
Could you describe more about "modify the libsubstrate.dylib name "

**Comment by baimour** [comment]
> 

This is a jailbreak dependency. It is injected when using esign signature. Without it, it may crash after restarting.

**Comment by powenn** [comment]
https://user-images.githubusercontent.com/72635554/181680749-ee62df90-6dfc-4dfa-934f-0c91d8e73007.MOV

It works for me in both environments 🤔

**Comment by baimour** [comment]
> Upload.from.GitHub.for.iOS.MOV 
> 它在两种环境中都适用于我🤔

The jailbreak state may crash for unknown reasons because libsubstrate.dylib is injected. You have to rename libsubstrate.dylib to open, maybe because of icleaner Pro? I don't know.
