### ISSUE TITLE
Crashes after pressing "permanent sign"

### ISSUE THREAD

**Issue by dxwil** [powenn/permasigneriOS#2]
After crashing it generates something, but not a valid deb that can be installed

https://user-images.githubusercontent.com/90563298/178036842-67ac779f-6b70-4f74-b478-b522fee6035d.MOV

**Comment by powenn** [comment]
That's a version which in developing few days ago,should got fixed in latest commit

**Comment by dxwil** [comment]
> That's a version which in developing few days ago,should got fixed in latest commit 

Where do I download the latest commit? If I redownload the one in pre-release the same crash happens.

**Comment by powenn** [comment]
> > That's a version which in developing few days ago,should got fixed in latest commit 
> 
> Where do I download the latest commit? If I redownload the one in pre-release the same crash happens.

In testing,coming soon

**Comment by dxwil** [comment]
> > > That's a version which in developing few days ago,should got fixed in latest commit 
> > 
> > Where do I download the latest commit? If I redownload the one in pre-release the same crash happens.
> 
> In testing,coming soon 

Oh I see, thanks
