### ISSUE TITLE
Flycast signing

### ISSUE THREAD

**Issue by Landxhent** [powenn/permasigneriOS#21]
Flycast cannot be signed on iPhone 12mini 14.1 taurine 1.1.6

**Comment by powenn** [comment]
Send me the file

**Comment by Landxhent** [comment]
> Send me the file 

[https://github.com/flyinghead/flycast/releases/download/v1.3/Flycast-1.3.ipa](flycast ipa)

**Comment by powenn** [comment]
It caused by version value in info plist then set to control file , you could try modify it manually to fix it , replace v1.3 to 1.3 in deb folder then repack it

**Comment by Landxhent** [comment]
> It caused by version value in info plist then set to control file , you could try modify it manually to fix it , replace v1.3 to 1.3 in deb folder then repack it 

Thanks a lot! It worked! Solved.
