### ISSUE TITLE
Installation error with newly signed iPA's on 0.1.12

### ISSUE THREAD

**Issue by theRealVLRS** [powenn/permasigneriOS#22]
I can sign the iPA's without an issue, but once I try to install the deb file with sileo or filza, I see an error called “Error: Unable to unregister /Applications/X.app”. I'm pretty sure that's related to uicache as I cannot see the app on my homescreen then. In comparison, installing permasigned iPA's which were made on 0.1.10 work as intended. I guess it's something that was introduced in the latest couple of updates that is causing the issue.

**Comment by powenn** [comment]
Send me file, some times caused by app itself

**Comment by powenn** [comment]
When you arledy have app installed like example.app with com.example bundle exists 
Then when you try to install example.app with com.example2 , you will get the error 
Try example2,example2,com.example2
