### ISSUE TITLE
Not possible to select an ipa file.

### ISSUE THREAD

**Issue by Landxhent** [powenn/permasigneriOS#27]
IPhone 12mini 14.1 taurine 1.1.5. 

Upon opening permasigner, no ipa file can be selected for signing. Checked on all versions from 0.1.10 to the  0.2.1.

Several apps have been successfully signed before on 0.1.10, however now it's impossible to sign any ipa. 

Have also tried to clean documents folder - no result.

**Comment by Landxhent** [comment]
Ah and also sometimes when attempt to select an ipa file, the whole app stuck.

**Comment by powenn** [comment]
Relaunch the app

**Comment by yueqingyou** [comment]
> Ah and also sometimes when attempt to select an ipa file, the whole app stuck.

I have also encountered it and it is 100% flashback, need to turn off the bold text to solve it
