### ISSUE TITLE
iP8 ios 14.6 checkra1n erro

### ISSUE THREAD

**Issue by taicracker** [powenn/permasigneriOS#3]
when signing with permasigneriOS , after installing app.deb can't open app on home screen.
Use ver 0.1.2 + 0.1.3 are all error
ver 0.1.1 opens the app ok when there is jb, but on reboot the app is unsigned, and can't be opened in a jb-free environment

**Comment by powenn** [comment]
Which ipa file you tested ,try test it with original permasigner then I might figure out the problems ,if permasigner works but mine not then it's my problem

**Comment by powenn** [comment]
Also, I guess there's some ipa files is impossible to get permanent sign if some contents wrong inside or just be difficult to reach for some reasons

**Comment by taicracker** [comment]
i tried signing it with original permasigner, but when i choose to sign with ldid the same problem occurs, also signing with option -c ( signcode ) the app works in jb state, reboot stock doesnt open the app Okay.
Also i use modified ipa, i modify its id ( Youtube ) com.google.youtube2 , but ipa works perfectly with Altstore

**Comment by powenn** [comment]
Actually this project is permasigner port for iOS , most parts using its code logic and reference on it  , so I will try to fix if permasigner fix it in future

**Comment by taicracker** [comment]
https://mega.nz/file/nRozmZxa#GSmqbwf-FnrE8oHwPHMo9X376TYUUOhqYXEKpybcjWg

**Comment by taicracker** [comment]
please help me try it on your device, link ipa

**Comment by powenn** [comment]
> please help me try it on your device, link ipa

Will try later , I have some stuff to do now

**Comment by powenn** [comment]
I noticed that all the frameworks binary are not executable after sign, I will modify codes to force rewrite its permission for testing

**Comment by powenn** [comment]
That was already un executable before sign

**Comment by powenn** [comment]
Reupload 0.1.3 release built with latest commit

**Comment by powenn** [comment]
@taicracker test results?

**Comment by taicracker** [comment]
> @taicracker test results?

yes i am retrying your latest release, and tried different ipa files, between original ipa and edited ipa i tried ipa youtube2 now it opens home screen i try start restart without jb see if it works or not.

**Comment by taicracker** [comment]
> @taicracker test results?

After I reboot, the application cannot be opened, I think the dylib components, the tweaks embedded in the application are not signed

**Comment by powenn** [comment]
I will try sign with ldid with entitlements

**Comment by powenn** [comment]
Second time reupload

**Comment by taicracker** [comment]
> Second time reupload 
> @taicracker 

Still no success with Youtube app, this time I use Youtube official ipa, I just embed 1 tieaks in the app, then sign it with your latest deb, but on restart it can't open the app  use

**Comment by powenn** [comment]
I think  decrypted apps from App Store  can't do that

**Comment by powenn** [comment]
Have u tried Altstore.ipa ?

**Comment by taicracker** [comment]
> Have u tried Altstore.ipa ?
please give me the file

**Comment by powenn** [comment]
https://cdn.altstore.io/file/altstore/apps/altstore/1_4_9.ipa

**Comment by taicracker** [comment]
https://github.com/34306/iPA/releases/tag/YT_CoreTrust

this version succeeds, it was signed before, but i don't know from which version of permasigner it was signed

**Comment by taicracker** [comment]
> 
altstore.ipa i signed it with your deb also can't open after reboot

**Comment by taicracker** [comment]
hello,
After I signed it with earlier version of permasiger it succeeded with youtube2 -> https://github.com/itsnebulalol/permasigner/tree/122fdd7fbc48cd049461c30979381dae56a83946

**Comment by powenn** [comment]
Trust me that won't be better , It was missing some parts

**Comment by taicracker** [comment]
> Trust me that won't be better , It was missing some parts
Every application I signed in the latest version of permasigner failed, but I succeeded in all of them on this version:
https://github.com/itsnebulalol/permasigner/tree/122fdd7fbc48cd049461c30979381dae56a83946

**Comment by powenn** [comment]
@taicracker Hi ,should work now

**Comment by taicracker** [comment]
> @taicracker Hi ,should work now 

Yeah!, it worked, but some ipa files when selected in permasigniOS it says Signer failed
i'm testing different ipa, succeeded with Youtube2, also found a way to fix login on youtube

**Comment by powenn** [comment]
Some app contents wrong inside
