### ISSUE TITLE
Crash of Unc0ver 

### ISSUE THREAD

**Issue by D1mar0n** [powenn/permasigneriOS#5]
Unfortunately, after leaving Jailbreak and trying to apply it again, everything ends with an error on the 18th paragraph. iPhone 12 Pro/Unc0ver 8.0.2/iOS 14.2
![4A7F537C-CB5B-4CCE-BBB4-9D3881D994F9](https://user-images.githubusercontent.com/35725771/178157733-5ce8f691-b295-4e21-81b0-e677a8f3b332.png)

**Comment by yueqingyou** [comment]
> 

You can use 6.1.1 which seems to work

**Comment by D1mar0n** [comment]
Installed version 6.2.0 - works great!

**Comment by powenn** [comment]
https://twitter.com/powen00hsiao/status/1546388726397698049?s=21&t=izbQpJcaRzGY0Ufd5IO3aQ
