### ISSUE TITLE
Apps not showing up

### ISSUE THREAD

**Issue by Merculous** [powenn/permasigneriOS#6]
I've tried to use your tool for its feature, however any app I "signed" does not show, even if I refresh the cache. I'm using 0.1.6. Anything I can do on my end to fix that?

**Comment by powenn** [comment]
https://twitter.com/powen00hsiao/status/1546011189540700161?s=21&t=emV444L4GndeS7esB4K3gg

**Comment by Merculous** [comment]
Ok, that seems to fix it. Thanks!
